image:
  repository: drumsergio/genieacs
  pullPolicy: IfNotPresent
  tag: "1.2.9"

service_http:
  type: ClusterIP
  port_http: 3000
service_cwmp:
  type: ClusterIP
  port_cwmp: 7547
service_nbi:
  type: ClusterIP
  port_nbi: 7557
service_fs:
  type: ClusterIP
  port_fs: 7567

ingress:
  enabled: true
  className: "" #Use the ingress controller of your cluster
  annotations: # If it is nginx-based... {}
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: # Modify according to your size
  #limits:
  #  cpu: 2
  #  memory: 4Gi
  requests:
    cpu: 500m
    memory: 2Gi

env:
  GENIEACS_UI_JWT_SECRET: changeme
  GENIEACS_CWMP_ACCESS_LOG_FILE: /var/log/genieacs/genieacs-cwmp-access.log
  GENIEACS_NBI_ACCESS_LOG_FILE: /var/log/genieacs/genieacs-nbi-access.log
  GENIEACS_FS_ACCESS_LOG_FILE: /var/log/genieacs/genieacs-fs-access.log
  GENIEACS_UI_ACCESS_LOG_FILE: /var/log/genieacs/genieacs-ui-access.log
  GENIEACS_DEBUG_FILE: /var/log/genieacs/genieacs-debug.yaml
  GENIEACS_EXT_DIR: /opt/genieacs/ext
  GENIEACS_MONGODB_CONNECTION_URL: mongodb://mongo/genieacs
